# Generated by Django 3.1.1 on 2020-09-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200917_2246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('text', 'group')},
        ),
    ]
